name: CMake Build Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build on ${{ matrix.os }} - Target: ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [RELEASE, TEST_IMGUI, TEST_CURL, TEST_FSTREAM, TEST_JSON]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y libwayland-dev wayland-protocols
          git clone https://github.com/glfw/glfw.git
          cd glfw
          cmake -B build -S . -DBUILD_SHARED_LIBS=ON
          sudo cmake --install build
          cd ..

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/glfw/glfw.git
          cd glfw
          cmake -B build -S . -DBUILD_SHARED_LIBS=ON
          cmake --install build
          cd ..

      - name: Configure CMake
        run: >
          cmake -B build -S . 
          -D${{ matrix.target }}=ON 
          -DCMAKE_BUILD_TYPE=Release 
          -DCMAKE_PREFIX_PATH="/usr/local"

      - name: Build
        run: cmake --build build --config Release
