name: Build All Targets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [RELEASE, TEST_IMGUI, TEST_CURL, TEST_FSTREAM, TEST_JSON]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure with CMake
        run: cmake -B build -S . -D${{ matrix.target }}=ON

      - name: Build
        run: cmake --build build --config Release
