name: build-windows # 워크플로우 이름

on:
  push:
    branches: [ "main" ] # main 브랜치 push 시 실행
  pull_request:
    branches: [ "main" ] # main 브랜치로 PR 시 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
            cmake_arch: "x64"
            cmake_options: "-DRELEASE=ON"
            build_config: "Release"

    steps:
    # 1. 코드 체크아웃 (서브모듈 포함)
    - name: Checkout repository including submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. Chocolatey를 사용하여 curl 설치 (Windows)
    - name: Install curl (Windows)
      if: runner.os == 'Windows'
      run: choco install curl --yes --force --ignore-checksums
      # shell: powershell # 기본 쉘 중 하나

    # 3. CMake 설정 단계
    - name: Configure CMake
      run: |
        # --- 방법 1: CMAKE_PREFIX_PATH 없이 시도 ---
        # choco가 환경을 잘 설정해 주었다면 이것만으로도 동작할 수 있습니다.
        cmake -S . -B build -G "${{ matrix.cmake_generator }}" -A ${{ matrix.cmake_arch }} ${{ matrix.cmake_options }}

        # --- 방법 2: 만약 방법 1이 실패하면 아래 주석을 풀고 경로를 확인/수정하세요 ---
        # Chocolatey의 실제 curl 설치 경로를 CMAKE_PREFIX_PATH로 지정합니다.
        # 예시 경로이며, 실제 경로는 다를 수 있습니다. (버전 등 확인 필요)
        # set CURL_ROOT=C:/ProgramData/chocolatey/lib/curl/ # 또는 더 구체적인 하위 폴더
        # cmake -S . -B build -G "${{ matrix.cmake_generator }}" -A ${{ matrix.cmake_arch }} ${{ matrix.cmake_options }} -DCMAKE_PREFIX_PATH="%CURL_ROOT%"

      shell: cmd # cmd 쉘 사용 시 주석은 REM 이나 :: 또는 아예 제거

    # 4. CMake 빌드 단계
    - name: Build project
      run: cmake --build build --config ${{ matrix.build_config }}
      shell: cmd

    # 5. (선택 사항) 빌드 결과물(아티팩트) 업로드
    - name: Upload artifact (Windows)
      if: runner.os == 'Windows' && success()
      uses: actions/upload-artifact@v4
      with:
        name: MarketDAQ-${{ matrix.os }}-${{ matrix.build_config }}
        path: build/${{ matrix.build_config }}/MarketDAQ.exe # 실제 생성된 실행 파일 경로 확인 필요