name: Build All Targets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [RELEASE, TEST_IMGUI, TEST_CURL, TEST_FSTREAM, TEST_JSON]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libglfw3-dev libglew-dev libgl1-mesa-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install glfw glew

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install glfw --confirm
          echo "⚠️ Note: May need manual CMake path setup if not found."

      - name: Configure with CMake
        run: cmake -B build -S . -D${{ matrix.target }}=ON

      - name: Build
        run: cmake --build build --config Release
